language: nix

os:
    - linux
    # - osx # Travis is saturated; see https://www.traviscistatus.com/

env:
  - EMACS_CI=emacs-24-3 LEDGER_VERSION=stable
  - EMACS_CI=emacs-24-4 LEDGER_VERSION=stable
  - EMACS_CI=emacs-24-5 LEDGER_VERSION=stable
  - EMACS_CI=emacs-25-1 LEDGER_VERSION=stable
  - EMACS_CI=emacs-25-2 LEDGER_VERSION=stable
  - EMACS_CI=emacs-25-3 LEDGER_VERSION=stable
  - EMACS_CI=emacs-26-1 LEDGER_VERSION=stable
  - EMACS_CI=emacs-26-2 LEDGER_VERSION=stable
  - EMACS_CI=emacs-26-3 LEDGER_VERSION=stable
  - EMACS_CI=emacs-snapshot LEDGER_VERSION=snapshot

matrix:
  allow_failures:
    - env: EMACS_CI=emacs-snapshot LEDGER_VERSION=snapshot

install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  # TODO: cache builds of this using cachix
  - nix-env -iA $LEDGER_VERSION -f tools

script:
  - emacs --version
  - ledger --version
  # Byte compilation is known to fail in Emacs < 26.1 due to ledger-flymake.el, which should
  # be packaged separately
  - emacs --eval "(setq byte-compile-error-on-warn (>= emacs-major-version 26))" -L .  --batch -f batch-byte-compile *.el
  - make -C test test-batch

after_script:
  - make -C test checkdoc

notifications:
  email: false
